export { default as WaterjetShopsIcon } from './WaterjetShopsIcon.vue'
export { default as WaterjetActionsIcon } from './WaterjetActionsIcon.vue'
export { default as WaterjetDeliveryIcon } from './WaterjetDeliveryIcon.vue'
export { default as WaterjetInstagramIcon } from './WaterjetInstagramIcon.vue'
export { default as WaterjetVkIcon } from './WaterjetVkIcon.vue'
export { default as WaterjetFacebookIcon } from './WaterjetFacebookIcon.vue'
export { default as WaterjetYoutubeIcon } from './WaterjetYoutubeIcon.vue'
export { default as WaterjetCartIcon } from './WaterjetCartIcon.vue'
export { default as WaterjetHeartIcon } from './WaterjetHeartIcon.vue'

